In [12]:
import io
from pathlib import Path

import chess
import chess.pgn
import chess.svg
import chess.engine
import pandas as pd
from PIL import Image
import cairosvg

import ipywidgets as widgets
from IPython.display import display, clear_output

from utils.opening_repository import OpeningRepository
from utils.game_enrichment_transformer import (
    GameEnrichmentTransformer,
    enriched_moves_to_flat_dicts,
)

In [13]:
STOCKFISH_PATH = "/opt/homebrew/bin/stockfish"  # Apple Silicon Mac
# STOCKFISH_PATH = "/usr/local/bin/stockfish"   # Intel Mac

OPENINGS_PATH = "openings_dataset/all.tsv"

ENGINE_DEPTH = 10

In [14]:
from utils.chesscom_repository import ChessComRepository

USERNAME = "bassisw"
MAX_GAMES = 20
SINCE_YEAR = 2025
SINCE_MONTH = 1

In [15]:
chesscom_repo = ChessComRepository(USERNAME)

games = []

for game_data in chesscom_repo.iter_all_games(
    since_year=SINCE_YEAR,
    since_month=SINCE_MONTH,
):
    if "pgn" not in game_data:
        continue

    games.append(game_data)

    if len(games) >= MAX_GAMES:
        break

print(f"Pulled {len(games)} games")

Pulled 20 games

In [16]:
if not games:
    raise RuntimeError("No games found. Check USERNAME, SINCE_YEAR, SINCE_MONTH.")

GAME_INDEX = 0

game_data = games[GAME_INDEX]

print(game_data["url"])
print(game_data.get("time_class"))
print(game_data.get("white"))
print(game_data.get("black"))

https://www.chess.com/game/live/130193958939
blitz
{'rating': 561, 'result': 'timeout', '@id': 'https://api.chess.com/pub/player/bassisw', 'username': 'bassisw', 'uuid': 'fb096f38-31f0-11ee-bdae-cfd83ad0aee0'}
{'rating': 732, 'result': 'win', '@id': 'https://api.chess.com/pub/player/sylvathur', 'username': 'Sylvathur', 'uuid': 'edd9d908-5d48-11eb-95c2-cd8c6efeb2ce'}

In [17]:
opening_repo = OpeningRepository(OPENINGS_PATH)

transformer = GameEnrichmentTransformer(
    stockfish_path=STOCKFISH_PATH,
    opening_repository=opening_repo,
    engine_limit=chess.engine.Limit(depth=ENGINE_DEPTH),
)

enriched_games = transformer.transform_games([game_data])
enriched_game = enriched_games[0]

moves_df = pd.DataFrame(enriched_moves_to_flat_dicts(enriched_games))

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 160)

game_info = {
    key: value
    for key, value in vars(enriched_game).items()
    if key != "moves"
}
game_info_df = pd.DataFrame([game_info])

display(game_info_df)

moves_df.head()

,uuid,url,white_username,black_username,white_rating,black_rating,white_result,black_result,result,time_class,time_control,rated,end_time,chesscom_white_accuracy,chesscom_black_accuracy,opening_eco,opening_name
0,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,bassisw,Sylvathur,561,732,timeout,win,0-1,blitz,180,False,1736455305,None,None,A17,"English Opening: Anglo-Indian Defense, Hedgehog System"

,game_uuid,game_url,ply,move_number,player_color,player_username,san,uci,fen_before,fen_after,eval_before_cp,eval_after_cp,eval_best_move_cp,eval_played_move_cp,move_cp_loss,best_move_uci,top_engine_moves,best_move_cp_gain,win_prob_before,win_prob_after,win_prob_loss,clock_before,clock_after,clock_spent,phase,position_type_tags,tactical_position,quiet_middlegame,complexity,number_of_legal_moves,eval_volatility_among_top_engine_lines,forcing_line_depth,low_gap_between_top_moves,engine_top_move_is_forcing,move_is_threat,is_capture,is_check,is_castling,is_promotion,in_opening_book,opening_eco,opening_name
0,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,1,1,white,bassisw,c4,c2c4,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1,rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1,45,12,45,11,34,e2e4,"[{'rank': 1, 'move_uci': 'e2e4', 'eval_cp': 45, 'line_uci': ['e2e4', 'c7c5', 'g1f3', 'e7e6', 'b1c3', 'b8c6', 'd2d4', 'c5d4', 'f3d4', 'g8f6', 'd4c6', 'b7c6']...",8,0.523170,0.506183,0.016987,180.0,180.0,0.0,opening,"[equal, quiet]",False,False,121.092121,20,9.092121,0,92.0,False,False,False,False,False,False,True,A10,English Opening
1,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,2,1,black,Sylvathur,Nf6,g8f6,rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1,rnbqkb1r/pppppppp/5n2/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 1 2,15,38,15,41,26,e7e5,"[{'rank': 1, 'move_uci': 'e7e5', 'eval_cp': 15, 'line_uci': ['e7e5', 'b1c3', 'g8f6', 'g1f3', 'b8c6', 'g2g3', 'd7d5', 'c4d5', 'f6d5', 'd2d3']}, {'rank': 2, '...",20,0.491631,0.478809,0.012822,180.0,180.0,0.0,opening,"[equal, quiet]",False,False,110.801234,20,10.801234,0,80.0,False,False,False,False,False,False,True,A15,English Opening: Anglo-Indian Defense
2,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,3,2,white,bassisw,Nc3,b1c3,rnbqkb1r/pppppppp/5n2/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 1 2,rnbqkb1r/pppppppp/5n2/8/2P5/2N5/PP1PPPPP/R1BQKBNR b KQkq - 2 2,41,20,41,20,21,d2d4,"[{'rank': 1, 'move_uci': 'd2d4', 'eval_cp': 41, 'line_uci': ['d2d4', 'e7e6', 'b1c3', 'f8b4', 'e2e3', 'b4c3', 'b2c3', 'b7b6', 'f2f3', 'd7d6', 'e3e4', 'b8c6',...",5,0.521113,0.510304,0.010809,180.0,178.8,1.2,opening,"[equal, quiet]",False,False,127.338708,22,10.338708,0,95.0,False,False,False,False,False,False,True,A16,"English Opening: Anglo-Indian Defense, Queen's Knight Variation"
3,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,4,2,black,Sylvathur,e6,e7e6,rnbqkb1r/pppppppp/5n2/8/2P5/2N5/PP1PPPPP/R1BQKBNR b KQkq - 2 2,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N5/PP1PPPPP/R1BQKBNR w KQkq - 0 3,20,41,20,37,17,e7e5,"[{'rank': 1, 'move_uci': 'e7e5', 'eval_cp': 20, 'line_uci': ['e7e5', 'g1f3', 'b8c6', 'g2g3', 'd7d5', 'c4d5', 'f6d5', 'f1g2', 'd5b6', 'd2d3', 'f8e7', 'c1e3',...",14,0.488842,0.477138,0.011704,180.0,178.8,1.2,opening,"[equal, quiet]",False,False,114.847546,22,6.847546,0,86.0,False,False,False,False,False,False,True,A17,"English Opening: Anglo-Indian Defense, Hedgehog System"
4,40fc279d-cec9-11ef-ad47-6cfe544c0428,https://www.chess.com/game/live/130193958939,5,3,white,bassisw,g3,g2g3,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N5/PP1PPPPP/R1BQKBNR w KQkq - 0 3,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N3P1/PP1PPP1P/R1BQKBNR b KQkq - 0 3,42,6,42,7,35,e2e4,"[{'rank': 1, 'move_uci': 'e2e4', 'eval_cp': 42, 'line_uci': ['e2e4', 'd7d5', 'e4e5', 'd5d4', 'e5f6', 'd4c3', 'f6g7', 'c3d2', 'c1d2', 'f8g7', 'd1c2', 'b7b6',...",7,0.521627,0.503091,0.018536,178.8,175.5,3.3,opening,"[equal, quiet]",False,False,122.299832,26,3.299832,0,93.0,False,False,False,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System"

In [18]:
pgn_text = game_data["pgn"]
game = chess.pgn.read_game(io.StringIO(pgn_text))

board = game.board()

board_states = [board.copy()]
moves = []

for move in game.mainline_moves():
    moves.append(move)
    board.push(move)
    board_states.append(board.copy())

print(f"Total moves / plies: {len(moves)}")

Total moves / plies: 60

In [19]:
def board_to_png_image(
    board: chess.Board,
    *,
    lastmove: chess.Move | None = None,
    size: int = 480,
):
    svg_data = chess.svg.board(
        board=board,
        lastmove=lastmove,
        size=size,
    )

    png_bytes = cairosvg.svg2png(bytestring=svg_data.encode("utf-8"))
    return Image.open(io.BytesIO(png_bytes))

In [20]:
MOVE_INFO_FIELD_ORDER = [
    "ply",
    "move_number",
    "player_color",
    "player_username",
    "san",
    "uci",
    "phase",
    "position_type_tags",
    "tactical_position",
    "quiet_middlegame",
    "complexity",
    "number_of_legal_moves",
    "eval_volatility_among_top_engine_lines",
    "forcing_line_depth",
    "low_gap_between_top_moves",
    "engine_top_move_is_forcing",
    "move_is_threat",
    "best_move_uci",
    "top_engine_moves",
    "best_move_cp_gain",
    "eval_before_cp",
    "eval_after_cp",
    "eval_best_move_cp",
    "eval_played_move_cp",
    "move_cp_loss",
    "win_prob_before",
    "win_prob_after",
    "win_prob_loss",
    "clock_before",
    "clock_after",
    "clock_spent",
    "is_capture",
    "is_check",
    "is_castling",
    "is_promotion",
    "opening_eco",
    "opening_name",
    "game_url",
    "game_uuid",
    "fen_before",
    "fen_after",
]


def ordered_move_columns(df: pd.DataFrame) -> list[str]:
    preferred = [column for column in MOVE_INFO_FIELD_ORDER if column in df.columns]
    extras = [column for column in df.columns if column not in preferred]
    return preferred + extras


def format_move_value(value):
    if isinstance(value, list):
        if not value:
            return ""
        if all(isinstance(item, str) for item in value):
            return ", ".join(value)
        return value

    if pd.isna(value):
        return None

    return value


def get_move_info(ply_index: int):
    """
    ply_index:
        0 = initial position
        1 = after first move
        2 = after second move
        ...
    """
    if ply_index == 0:
        return {
            "Position": "Initial position",
            "Move": None,
        }

    row = moves_df.iloc[ply_index - 1]

    return {
        column: format_move_value(row[column])
        for column in ordered_move_columns(moves_df)
    }

In [21]:
move_slider = widgets.IntSlider(
    value=0,
    min=0,
    max=len(board_states) - 1,
    step=1,
    description="Ply",
    continuous_update=False,
)

prev_button = widgets.Button(description="← Previous")
next_button = widgets.Button(description="Next →")

output = widgets.Output()


def render_position(ply_index: int):
    with output:
        clear_output(wait=True)

        board = board_states[ply_index]
        lastmove = moves[ply_index - 1] if ply_index > 0 else None

        image = board_to_png_image(board, lastmove=lastmove)
        display(image)

        info = get_move_info(ply_index)

        info_df = pd.DataFrame(
            [{"field": key, "value": value} for key, value in info.items()]
        )

        display(info_df)


def on_slider_change(change):
    if change["name"] == "value":
        render_position(change["new"])


def go_previous(_):
    move_slider.value = max(move_slider.min, move_slider.value - 1)


def go_next(_):
    move_slider.value = min(move_slider.max, move_slider.value + 1)


move_slider.observe(on_slider_change)

prev_button.on_click(go_previous)
next_button.on_click(go_next)

display(widgets.HBox([prev_button, next_button]))
display(move_slider)
display(output)

render_position(0)

HBox(children=(Button(description='← Previous', style=ButtonStyle()), Button(description='Next →', style=Butto…

IntSlider(value=0, continuous_update=False, description='Ply', max=60)

Output()

In [22]:
moves_df[ordered_move_columns(moves_df)]

,ply,move_number,player_color,player_username,san,uci,phase,position_type_tags,tactical_position,quiet_middlegame,complexity,number_of_legal_moves,eval_volatility_among_top_engine_lines,forcing_line_depth,low_gap_between_top_moves,engine_top_move_is_forcing,move_is_threat,best_move_uci,top_engine_moves,best_move_cp_gain,eval_before_cp,eval_after_cp,eval_best_move_cp,eval_played_move_cp,move_cp_loss,win_prob_before,win_prob_after,win_prob_loss,clock_before,clock_after,clock_spent,is_capture,is_check,is_castling,is_promotion,opening_eco,opening_name,game_url,game_uuid,fen_before,fen_after,in_opening_book
0,1,1,white,bassisw,c4,c2c4,opening,"[equal, quiet]",False,False,121.092121,20,9.092121,0,92.0,False,False,e2e4,"[{'rank': 1, 'move_uci': 'e2e4', 'eval_cp': 45, 'line_uci': ['e2e4', 'c7c5', 'g1f3', 'e7e6', 'b1c3', 'b8c6', 'd2d4', 'c5d4', 'f3d4', 'g8f6', 'd4c6', 'b7c6']...",8,45,12,45,11,34,0.523170,0.506183,0.016987,180.0,180.0,0.0,False,False,False,False,A10,English Opening,https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1,rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1,True
1,2,1,black,Sylvathur,Nf6,g8f6,opening,"[equal, quiet]",False,False,110.801234,20,10.801234,0,80.0,False,False,e7e5,"[{'rank': 1, 'move_uci': 'e7e5', 'eval_cp': 15, 'line_uci': ['e7e5', 'b1c3', 'g8f6', 'g1f3', 'b8c6', 'g2g3', 'd7d5', 'c4d5', 'f6d5', 'd2d3']}, {'rank': 2, '...",20,15,38,15,41,26,0.491631,0.478809,0.012822,180.0,180.0,0.0,False,False,False,False,A15,English Opening: Anglo-Indian Defense,https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1,rnbqkb1r/pppppppp/5n2/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 1 2,True
2,3,2,white,bassisw,Nc3,b1c3,opening,"[equal, quiet]",False,False,127.338708,22,10.338708,0,95.0,False,False,d2d4,"[{'rank': 1, 'move_uci': 'd2d4', 'eval_cp': 41, 'line_uci': ['d2d4', 'e7e6', 'b1c3', 'f8b4', 'e2e3', 'b4c3', 'b2c3', 'b7b6', 'f2f3', 'd7d6', 'e3e4', 'b8c6',...",5,41,20,41,20,21,0.521113,0.510304,0.010809,180.0,178.8,1.2,False,False,False,False,A16,"English Opening: Anglo-Indian Defense, Queen's Knight Variation",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pppppppp/5n2/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 1 2,rnbqkb1r/pppppppp/5n2/8/2P5/2N5/PP1PPPPP/R1BQKBNR b KQkq - 2 2,True
3,4,2,black,Sylvathur,e6,e7e6,opening,"[equal, quiet]",False,False,114.847546,22,6.847546,0,86.0,False,False,e7e5,"[{'rank': 1, 'move_uci': 'e7e5', 'eval_cp': 20, 'line_uci': ['e7e5', 'g1f3', 'b8c6', 'g2g3', 'd7d5', 'c4d5', 'f6d5', 'f1g2', 'd5b6', 'd2d3', 'f8e7', 'c1e3',...",14,20,41,20,37,17,0.488842,0.477138,0.011704,180.0,178.8,1.2,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pppppppp/5n2/8/2P5/2N5/PP1PPPPP/R1BQKBNR b KQkq - 2 2,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N5/PP1PPPPP/R1BQKBNR w KQkq - 0 3,True
4,5,3,white,bassisw,g3,g2g3,opening,"[equal, quiet]",False,False,122.299832,26,3.299832,0,93.0,False,False,e2e4,"[{'rank': 1, 'move_uci': 'e2e4', 'eval_cp': 42, 'line_uci': ['e2e4', 'd7d5', 'e4e5', 'd5d4', 'e5f6', 'd4c3', 'f6g7', 'c3d2', 'c1d2', 'f8g7', 'd1c2', 'b7b6',...",7,42,6,42,7,35,0.521627,0.503091,0.018536,178.8,175.5,3.3,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N5/PP1PPPPP/R1BQKBNR w KQkq - 0 3,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N3P1/PP1PPP1P/R1BQKBNR b KQkq - 0 3,False
5,6,3,black,Sylvathur,c5,c7c5,opening,"[equal, quiet]",False,False,123.653837,28,8.653837,0,87.0,False,False,d7d5,"[{'rank': 1, 'move_uci': 'd7d5', 'eval_cp': 6, 'line_uci': ['d7d5', 'd2d4', 'd5c4', 'g1f3', 'c7c5', 'f1g2', 'b8c6', 'd1a4', 'c5d4', 'f3d4', 'd8d4', 'g2c6', ...",13,6,39,6,41,35,0.496652,0.478252,0.018400,178.8,177.5,1.3,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pppp1ppp/4pn2/8/2P5/2N3P1/PP1PPP1P/R1BQKBNR b KQkq - 0 3,rnbqkb1r/pp1p1ppp/4pn2/2p5/2P5/2N3P1/PP1PPP1P/R1BQKBNR w KQkq - 0 4,False
6,7,4,white,bassisw,Bg2,f1g2,opening,"[equal, quiet]",False,False,119.577762,26,15.577762,0,78.0,False,False,g1f3,"[{'rank': 1, 'move_uci': 'g1f3', 'eval_cp': 39, 'line_uci': ['g1f3', 'f8e7', 'f1g2', 'd7d5', 'c4d5', 'e6d5', 'd2d4', 'h7h6', 'd4c5', 'e7c5', 'e1g1', 'e8g8',...",22,39,20,39,19,20,0.520084,0.510304,0.009780,175.5,173.6,1.9,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pp1p1ppp/4pn2/2p5/2P5/2N3P1/PP1PPP1P/R1BQKBNR w KQkq - 0 4,rnbqkb1r/pp1p1ppp/4pn2/2p5/2P5/2N3P1/PP1PPPBP/R1BQK1NR b KQkq - 1 4,False
7,8,4,black,Sylvathur,Nc6,b8c6,opening,"[equal, quiet]",False,False,120.897712,26,11.897712,0,83.0,False,False,d7d5,"[{'rank': 1, 'move_uci': 'd7d5', 'eval_cp': 20, 'line_uci': ['d7d5', 'd1b3', 'b8c6', 'c4d5', 'c6d4', 'b3d1', 'e6d5', 'e2e3', 'd4c6', 'd2d4']}, {'rank': 2, '...",17,20,37,20,35,15,0.488842,0.479366,0.009476,177.5,162.1,15.4,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,rnbqkb1r/pp1p1ppp/4pn2/2p5/2P5/2N3P1/PP1PPPBP/R1BQK1NR b KQkq - 1 4,r1bqkb1r/pp1p1ppp/2n1pn2/2p5/2P5/2N3P1/PP1PPPBP/R1BQK1NR w KQkq - 2 5,False
8,9,5,white,bassisw,Nf3,g1f3,opening,"[equal, quiet]",False,False,137.993825,31,8.993825,0,98.0,False,False,g1f3,"[{'rank': 1, 'move_uci': 'g1f3', 'eval_cp': 34, 'line_uci': ['g1f3', 'd7d5', 'c4d5', 'e6d5', 'd2d4', 'c8e6', 'e1g1', 'h7h6', 'e2e3', 'f8e7', 'd4c5', 'e7c5',...",2,34,45,34,36,0,0.517511,0.523170,-0.005658,173.6,171.5,2.1,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1bqkb1r/pp1p1ppp/2n1pn2/2p5/2P5/2N3P1/PP1PPPBP/R1BQK1NR w KQkq - 2 5,r1bqkb1r/pp1p1ppp/2n1pn2/2p5/2P5/2N2NP1/PP1PPPBP/R1BQK2R b KQkq - 3 5,False
9,10,5,black,Sylvathur,Qb6,d8b6,opening,"[equal, quiet]",False,False,134.027682,31,4.027682,0,99.0,False,False,d7d5,"[{'rank': 1, 'move_uci': 'd7d5', 'eval_cp': 50, 'line_uci': ['d7d5', 'c4d5', 'e6d5', 'd2d4', 'c8e6', 'e1g1', 'h7h6', 'b2b3', 'f8e7', 'c1b2', 'e8g8', 'a1c1']...",1,50,52,50,54,4,0.472129,0.471017,0.001112,162.1,160.4,1.7,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1bqkb1r/pp1p1ppp/2n1pn2/2p5/2P5/2N2NP1/PP1PPPBP/R1BQK2R b KQkq - 3 5,r1b1kb1r/pp1p1ppp/1qn1pn2/2p5/2P5/2N2NP1/PP1PPPBP/R1BQK2R w KQkq - 4 6,False
10,11,6,white,bassisw,b3,b2b3,opening,"[equal, quiet]",False,False,131.988877,31,4.988877,0,96.0,False,False,e1g1,"[{'rank': 1, 'move_uci': 'e1g1', 'eval_cp': 58, 'line_uci': ['e1g1', 'f8e7', 'b2b3', 'd7d6', 'c3a4', 'b6a6', 'd2d4', 'e8g8', 'd4c5', 'd6c5']}, {'rank': 2, '...",4,58,56,58,54,4,0.529849,0.528822,0.001027,171.5,166.5,5.0,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp1p1ppp/1qn1pn2/2p5/2P5/2N2NP1/PP1PPPBP/R1BQK2R w KQkq - 4 6,r1b1kb1r/pp1p1ppp/1qn1pn2/2p5/2P5/1PN2NP1/P2PPPBP/R1BQK2R b KQkq - 0 6,False
11,12,6,black,Sylvathur,d5,d7d5,opening,"[equal, quiet]",False,False,138.640988,34,8.640988,0,96.0,False,False,d7d5,"[{'rank': 1, 'move_uci': 'd7d5', 'eval_cp': 51, 'line_uci': ['d7d5', 'c4d5', 'e6d5', 'c1b2', 'f8e7', 'c3a4', 'b6a5', 'b2c3', 'a5a6', 'c3f6', 'e7f6', 'a4c5']...",4,51,53,51,41,0,0.471573,0.470460,0.001112,160.4,149.6,10.8,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp1p1ppp/1qn1pn2/2p5/2P5/1PN2NP1/P2PPPBP/R1BQK2R b KQkq - 0 6,r1b1kb1r/pp3ppp/1qn1pn2/2pp4/2P5/1PN2NP1/P2PPPBP/R1BQK2R w KQkq - 0 7,False
12,13,7,white,bassisw,cxd5,c4d5,opening,"[equal, tactical]",True,False,127.257180,31,7.257180,2,87.0,True,False,c4d5,"[{'rank': 1, 'move_uci': 'c4d5', 'eval_cp': 62, 'line_uci': ['c4d5', 'e6d5', 'c1b2', 'd5d4', 'c3a4', 'b6a5', 'e1g1', 'b7b5', 'e2e3', 'b5a4']}, {'rank': 2, '...",13,62,45,62,47,15,0.531902,0.523170,0.008732,166.5,156.8,9.7,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn1pn2/2pp4/2P5/1PN2NP1/P2PPPBP/R1BQK2R w KQkq - 0 7,r1b1kb1r/pp3ppp/1qn1pn2/2pP4/8/1PN2NP1/P2PPPBP/R1BQK2R b KQkq - 0 7,False
13,14,7,black,Sylvathur,Nxd5,f6d5,opening,"[equal, tactical]",True,False,175.786562,37,47.786562,1,90.0,True,False,e6d5,"[{'rank': 1, 'move_uci': 'e6d5', 'eval_cp': 47, 'line_uci': ['e6d5', 'c1b2', 'd5d4', 'c3a4', 'b6a5', 'e2e3', 'f8e7', 'e1g1', 'e8g8', 'e3d4', 'c5d4', 'f3d4',...",10,47,43,47,44,0,0.473798,0.476024,-0.002226,149.6,146.7,2.9,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn1pn2/2pP4/8/1PN2NP1/P2PPPBP/R1BQK2R b KQkq - 0 7,r1b1kb1r/pp3ppp/1qn1p3/2pn4/8/1PN2NP1/P2PPPBP/R1BQK2R w KQkq - 0 8,False
14,15,8,white,bassisw,Nxd5,c3d5,opening,"[equal, tactical]",True,False,118.614456,30,10.614456,0,78.0,False,False,c1b2,"[{'rank': 1, 'move_uci': 'c1b2', 'eval_cp': 49, 'line_uci': ['c1b2', 'd5c3', 'b2c3', 'f7f6', 'e2e3', 'f8e7', 'e1g1', 'e8g8', 'd1e2']}, {'rank': 2, 'move_uci...",22,49,10,49,8,41,0.525226,0.505152,0.020073,156.8,145.3,11.5,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn1p3/2pn4/8/1PN2NP1/P2PPPBP/R1BQK2R w KQkq - 0 8,r1b1kb1r/pp3ppp/1qn1p3/2pN4/8/1P3NP1/P2PPPBP/R1BQK2R b KQkq - 0 8,False
15,16,8,black,Sylvathur,exd5,e6d5,opening,"[equal, tactical]",True,False,269.196246,32,236.196246,1,0.0,True,False,e6d5,"[{'rank': 1, 'move_uci': 'e6d5', 'eval_cp': 10, 'line_uci': ['e6d5', 'e1g1', 'f8e7', 'c1a3', 'b6a5', 'a3b2', 'd5d4', 'e2e3', 'e7f6', 'e3d4', 'c5d4', 'd1e1',...",497,10,9,10,8,0,0.494420,0.494978,-0.000558,146.7,145.5,1.2,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn1p3/2pN4/8/1P3NP1/P2PPPBP/R1BQK2R b KQkq - 0 8,r1b1kb1r/pp3ppp/1qn5/2pp4/8/1P3NP1/P2PPPBP/R1BQK2R w KQkq - 0 9,False
16,17,9,white,bassisw,d3,d2d3,opening,"[equal, quiet]",False,False,126.885618,25,1.885618,0,100.0,False,False,c1a3,"[{'rank': 1, 'move_uci': 'c1a3', 'eval_cp': 6, 'line_uci': ['c1a3', 'f8e7', 'e1g1', 'd5d4', 'e2e3', 'd4e3', 'f2e3', 'e8g8', 'f3h4', 'c6b4', 'h4f5']}, {'rank...",0,6,-27,6,-26,32,0.503091,0.486092,0.017000,145.3,134.4,10.9,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn5/2pp4/8/1P3NP1/P2PPPBP/R1BQK2R w KQkq - 0 9,r1b1kb1r/pp3ppp/1qn5/2pp4/8/1P1P1NP1/P3PPBP/R1BQK2R b KQkq - 0 9,False
17,18,9,black,Sylvathur,Be6,c8e6,opening,"[equal, quiet]",False,False,132.416298,36,9.416298,0,87.0,False,False,f8e7,"[{'rank': 1, 'move_uci': 'f8e7', 'eval_cp': -39, 'line_uci': ['f8e7', 'e1g1', 'e8g8', 'c1g5', 'f7f6', 'g5d2']}, {'rank': 2, 'move_uci': 'c8g4', 'eval_cp': -...",13,-39,45,-39,47,86,0.521748,0.474911,0.046837,145.5,137.9,7.6,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r1b1kb1r/pp3ppp/1qn5/2pp4/8/1P1P1NP1/P3PPBP/R1BQK2R b KQkq - 0 9,r3kb1r/pp3ppp/1qn1b3/2pp4/8/1P1P1NP1/P3PPBP/R1BQK2R w KQkq - 1 10,False
18,19,10,white,bassisw,O-O,e1g1,opening,"[equal, quiet]",False,False,102.927249,32,25.927249,0,45.0,False,False,f3g5,"[{'rank': 1, 'move_uci': 'f3g5', 'eval_cp': 55, 'line_uci': ['f3g5', 'f8e7', 'g5e6', 'f7e6', 'e1g1', 'e7f6', 'a1b1', 'e8g8', 'e2e4', 'a8d8', 'e4d5', 'e6d5',...",55,55,-10,55,-5,60,0.528308,0.494848,0.033461,134.4,132.4,2.0,False,False,True,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3kb1r/pp3ppp/1qn1b3/2pp4/8/1P1P1NP1/P3PPBP/R1BQK2R w KQkq - 1 10,r3kb1r/pp3ppp/1qn1b3/2pp4/8/1P1P1NP1/P3PPBP/R1BQ1RK1 b kq - 2 10,False
19,20,10,black,Sylvathur,Nb4,c6b4,opening,"[equal, quiet]",False,False,123.938795,39,19.938795,0,65.0,False,False,h7h6,"[{'rank': 1, 'move_uci': 'h7h6', 'eval_cp': -8, 'line_uci': ['h7h6', 'c1b2', 'd5d4', 'f3d2', 'f8e7', 'f2f4', 'e8g8', 'f4f5', 'e6d7', 'd2c4', 'b6c7']}, {'ran...",35,-8,117,-8,127,135,0.504464,0.435083,0.069381,137.9,136.1,1.8,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3kb1r/pp3ppp/1qn1b3/2pp4/8/1P1P1NP1/P3PPBP/R1BQ1RK1 b kq - 2 10,r3kb1r/pp3ppp/1q2b3/2pp4/1n6/1P1P1NP1/P3PPBP/R1BQ1RK1 w kq - 3 11,False
20,21,11,white,bassisw,Bf4,c1f4,middlegame,"[equal, quiet, quiet_middlegame]",False,True,129.546061,29,4.546061,0,96.0,False,False,a2a3,"[{'rank': 1, 'move_uci': 'a2a3', 'eval_cp': 118, 'line_uci': ['a2a3', 'b4c6', 'f3g5', 'f8e7', 'g5e6', 'f7e6', 'e2e4', 'd5e4', 'g2e4', 'e7f6', 'a1b1', 'e8g8'...",4,118,65,118,64,54,0.560502,0.533441,0.027060,132.4,120.2,12.2,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3kb1r/pp3ppp/1q2b3/2pp4/1n6/1P1P1NP1/P3PPBP/R1BQ1RK1 w kq - 3 11,r3kb1r/pp3ppp/1q2b3/2pp4/1n3B2/1P1P1NP1/P3PPBP/R2Q1RK1 b kq - 4 11,False
21,22,11,black,Sylvathur,Bd6,f8d6,middlegame,"[equal, quiet, quiet_middlegame]",False,True,136.247219,37,1.247219,0,98.0,False,False,f8d6,"[{'rank': 1, 'move_uci': 'f8d6', 'eval_cp': 63, 'line_uci': ['f8d6', 'f4d6', 'b6d6', 'd3d4', 'e8g8', 'd4c5', 'd6c5', 'f3g5', 'h7h6', 'g5e6', 'f7e6']}, {'ran...",2,63,66,63,66,3,0.464904,0.463238,0.001665,136.1,129.8,6.3,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3kb1r/pp3ppp/1q2b3/2pp4/1n3B2/1P1P1NP1/P3PPBP/R2Q1RK1 b kq - 4 11,r3k2r/pp3ppp/1q1bb3/2pp4/1n3B2/1P1P1NP1/P3PPBP/R2Q1RK1 w kq - 5 12,False
22,23,12,white,bassisw,Bxd6,f4d6,middlegame,"[equal, tactical]",True,False,137.775681,32,11.775681,2,92.0,True,False,f4d6,"[{'rank': 1, 'move_uci': 'f4d6', 'eval_cp': 65, 'line_uci': ['f4d6', 'b6d6', 'd3d4', 'e8g8', 'd4c5', 'd6c5', 'a1c1', 'c5b6', 'd1d2', 'b4c6', 'f1d1', 'h7h6',...",8,65,68,65,67,0,0.533441,0.534980,-0.001539,120.2,117.0,3.2,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/1q1bb3/2pp4/1n3B2/1P1P1NP1/P3PPBP/R2Q1RK1 w kq - 5 12,r3k2r/pp3ppp/1q1Bb3/2pp4/1n6/1P1P1NP1/P3PPBP/R2Q1RK1 b kq - 0 12,False
23,24,12,black,Sylvathur,Qxd6,b6d6,middlegame,"[equal, tactical]",True,False,234.918744,35,198.918744,1,0.0,True,False,b6d6,"[{'rank': 1, 'move_uci': 'b6d6', 'eval_cp': 67, 'line_uci': ['b6d6', 'd3d4', 'e8g8', 'd4c5', 'd6c5', 'a1c1', 'c5e7', 'd1d2', 'h7h6']}, {'rank': 2, 'move_uci...",410,67,55,67,60,0,0.462684,0.469348,-0.006665,129.8,128.6,1.2,True,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/1q1Bb3/2pp4/1n6/1P1P1NP1/P3PPBP/R2Q1RK1 b kq - 0 12,r3k2r/pp3ppp/3qb3/2pp4/1n6/1P1P1NP1/P3PPBP/R2Q1RK1 w kq - 0 13,False
24,25,13,white,bassisw,e4,e2e4,middlegame,"[equal, quiet, quiet_middlegame]",False,True,122.921608,25,4.921608,0,93.0,False,False,d3d4,"[{'rank': 1, 'move_uci': 'd3d4', 'eval_cp': 48, 'line_uci': ['d3d4', 'e8g8', 'd4c5', 'd6c5', 'a1c1', 'c5b6', 'a2a3', 'b4c6', 'f3g5', 'h7h6', 'g5e6', 'f7e6',...",7,48,-46,48,-39,87,0.524712,0.476316,0.048396,117.0,112.8,4.2,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/3qb3/2pp4/1n6/1P1P1NP1/P3PPBP/R2Q1RK1 w kq - 0 13,r3k2r/pp3ppp/3qb3/2pp4/1n2P3/1P1P1NP1/P4PBP/R2Q1RK1 b kq - 0 13,False
25,26,13,black,Sylvathur,d4,d5d4,middlegame,"[equal, tactical]",True,False,136.928388,46,13.928388,1,76.0,True,False,d5e4,"[{'rank': 1, 'move_uci': 'd5e4', 'eval_cp': -25, 'line_uci': ['d5e4', 'f3g5', 'e4d3', 'g2b7', 'a8d8', 'd1h5', 'g7g6', 'h5h6', 'd6e7', 'b7g2']}, {'rank': 2, ...",24,-25,156,-25,151,176,0.513946,0.413821,0.100125,128.6,115.7,12.9,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/3qb3/2pp4/1n2P3/1P1P1NP1/P4PBP/R2Q1RK1 b kq - 0 13,r3k2r/pp3ppp/3qb3/2p5/1n1pP3/1P1P1NP1/P4PBP/R2Q1RK1 w kq - 0 14,False
26,27,14,white,bassisw,a3,a2a3,middlegame,"[equal, quiet, quiet_middlegame]",False,True,159.249907,24,37.249907,0,98.0,False,False,f3g5,"[{'rank': 1, 'move_uci': 'f3g5', 'eval_cp': 147, 'line_uci': ['f3g5', 'e8g8', 'a2a3', 'b4c6', 'f2f4', 'f7f6', 'g5e6', 'd6e6', 'a1c1', 'b7b6', 'b3b4', 'c5b4'...",2,147,140,147,145,2,0.575168,0.571639,0.003529,112.8,102.7,10.1,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/3qb3/2p5/1n1pP3/1P1P1NP1/P4PBP/R2Q1RK1 w kq - 0 14,r3k2r/pp3ppp/3qb3/2p5/1n1pP3/PP1P1NP1/5PBP/R2Q1RK1 b kq - 0 14,False
27,28,14,black,Sylvathur,Nc6,b4c6,middlegame,"[equal, quiet, quiet_middlegame]",False,True,247.937723,49,115.937723,0,83.0,False,False,b4a6,"[{'rank': 1, 'move_uci': 'b4a6', 'eval_cp': 122, 'line_uci': ['b4a6', 'f3g5', 'd6d7', 'g5e6', 'd7e6', 'f2f4', 'e8g8', 'e4e5', 'a6c7', 'g2b7']}, {'rank': 2, ...",17,122,135,122,137,15,0.432342,0.425235,0.007107,115.7,109.8,5.9,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/3qb3/2p5/1n1pP3/PP1P1NP1/5PBP/R2Q1RK1 b kq - 0 14,r3k2r/pp3ppp/2nqb3/2p5/3pP3/PP1P1NP1/5PBP/R2Q1RK1 w kq - 1 15,False
28,29,15,white,bassisw,Rc1,a1c1,middlegame,"[equal, quiet, quiet_middlegame]",False,True,101.171052,25,22.171052,0,54.0,False,False,f3g5,"[{'rank': 1, 'move_uci': 'f3g5', 'eval_cp': 138, 'line_uci': ['f3g5', 'e8g8', 'f2f4', 'a8c8', 'd1h5', 'h7h6', 'e4e5', 'd6d7', 'g5e4']}, {'rank': 2, 'move_uc...",46,138,76,138,95,43,0.570629,0.539079,0.031550,102.7,98.0,4.7,False,False,False,False,A17,"English Opening: Anglo-Indian Defense, Hedgehog System",https://www.chess.com/game/live/130193958939,40fc279d-cec9-11ef-ad47-6cfe544c0428,r3k2r/pp3ppp/2nqb3/2p5/3pP3/PP1P1NP1/5PBP/R2Q1RK1 w kq - 1 15,r3k2r/pp3ppp/2nqb3/2p5/3pP3/PP1P1NP1/5PBP/2RQ1RK1 b kq - 2 15,False